### PR TITLE
fix(uiSref): run update when input properties change

### LINKED ISSUE #140: Changes to uiSref target state are not propagated to other directives
If I have a dynamic binding to uiSref, as follows:

```html
<a
  [uiSref]="someDynamicLink"
  uiSrefActive="active"
>Some Dynamic Link
</a>
```

Changes to ```someDynamicLink``` do not result in directives like uiSrefActive updating themselves. E.g. if the value of someDynamicLink is changed, the active state of the link is not updated to reflect whether the new value matches the current path.

The problem seems to lie with the strange way the uiSref directive defines its input properties. There is an ```@input('uiSref')``` decorator applied to the ```state``` property, but changes to this field do not cause any event to be emitted on the ```targetState$``` subject. There is a setter called ```"uiSref"``` and marked ```@internalapi```, which wraps ```state``` and *does* emit an event on ```targetState$```, but this will not be called by Angular, as it is not marked as an input.

I was able to get things working by replacing:

```ts
@Input('uiSref') state: string;
```

With...

```ts
private _state: string;

/**
 * `@Input('uiSref')` The name of the state to link to
 *
 * ```html
 * <a uiSref="hoome">Home</a>
 * ```
 */
@Input('uiSref') 
set state(val) {
  this._state = val;
  this.update();
}

get state() {
  return this._state;
}
```

But I'm not clear on what purpose the ```"uiSref"``` property setter serves, and whether there was any rationale behind it firing updates rather than ```state```?

### PR DESCRIPTION
**Pull request by jonrimmer**
Fixes #140

### CODE REVIEW

File: src/directives/uiSref.ts [hunk 1]
```diff
@@ -71,14 +71,22 @@ export class AnchorUISref {
...
   /**
    * `@Input('uiSref')` The name of the state to link to
    *
    * ```html
    * <a uiSref="hoome">Home</a>
    * ```
    */
-  @Input('uiSref') state: string;
+  @Input('uiSref')
+  get state(): string {
```
Comment (aitboudad) [inline src/directives/uiSref.ts]: I suggest to keep the old way and relying to `ngOnChanges` unstead

**Comment by jonrimmer** [comment]
@aitboudad I've done as you suggested. This does require keeping the ```.update()``` call in each of the internal API setters.
